# Présentation : configuration du composant Validator.
# Rôle : déterminer la manière dont Symfony charge et applique les contraintes de validation.
framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
