# Présentation : configuration de la barre et du profiler en développement.
# Rôle : fournir des informations sur les requêtes sans exposer ces outils en production.
when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
